#include <iostream>

class Test
{
//by default compiler generates following functions for a class :
//C++03 :
//a. Default Constructor : Test() {}
//b. Destructor : ~Test() {}
//c. Copy Constructor : Test(const Test& existingObj) {}
//d. Assignment Operator : Test& operator=(const Test& existingObj) {}

//C++11 :
//e. Move Constructor : Test(Test&& rvalueReference) {} : default move constructor is generated by compiler if b, c, d & f are not specified by class author.
//f. Move Assignment Operator : Test& operator=(Test&& rvalueReference) {} : default move assignment operator is generated by compiler if b, c, d & e are not specified by class author.
};

int main()
{
    return 0;
}
